config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  get 'resources' => 'pages#resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  root 'home#index'
  resources :posts
  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates_presence_of :name
  validates_length_of :name, :within => 2..20
  validates_presence_of :body
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :admin_user
  has_many :comments, :dependent => :destroy
  validates :title, :presence => true
  validates_length_of :body, :minimum => 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts
  before_action :site_search

  def all_categories
	  @categories = Category.all
  end
  def all_posts
    @posts = Post.all
  end
  def site_search
    @q = Post.search(params[:q])
    @search_result = @q.result(distinct: true)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  def index
    @categories = Category.all
  end

  def category_params
    params.require(:category).permit(:name)
  end
  # GET /categories/1
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts
  end

end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      ;flash[:notice] = 'Comment was successfully created.'
      redirect_to(@comment.post)
		else
      flash[:notice] = "Error creating post comment: #{@comment.errors}"
      redirect_to(@comment.post)
		end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = Post.search(params[:q])
    @posts = @q.result(distinct: true)
  end
  def new
    @post = Post.new
    @categories = Category.all
  end
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :author_id)
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, :notice => "Your post has been saved"
    else
      render "new"
    end
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
			redirect_to post_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
  end
  def show
    @post = Post.find(params[:id])
    @users = AdminUser.all
    @post_comment = Comment.new(:post => @post)
  end
  def destroy
    @post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<ul>
<% @categories.each do |category| %>
  <li><%= link_to category.name,category %></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
  <div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
      <p class="meta">July 09, 2018 Posted by
        <a href="#">Someone</a>
      </p>
      <p class="links">
        <a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a>
      </p>
    </div>
  </div>
<% end.empty? %>
  <p style="color:#ffffff;">Sorry, there are no posts in this category</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :comment_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :comment_email %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id, id: :comment_post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.email %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
      <p class="meta">July 09, 2018 Posted by <%= post.admin_user.name%></p>
      <p class="links">
        <%= link_to "Read More",post %>
      </p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrubyblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "partials/header" %>

      <div id="page">
        <div id="page-bgtop">
          <div id="page-bgbtm">
            <!-- start #content -->
            <div id="content">
              <div class="flash-message">
                <% flash.each do |key,value| %>
                  <p><%= value %></p>
                <% end %>
              </div>
              <%= yield %>
              <!--main view-->
              <div style="clear: both;">&nbsp;</div>
            </div>
            <!-- end #content -->
            <%= render "partials/sidebar" %>
            <div style="clear: both;">&nbsp;</div>
          </div>
        </div>
      </div>

      <div id="footer">
        <p>&copy; 2018 - My Ruby Blog - Sample Project</p>
      </div>
    </div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="post">
  <h1>About Myrubyblog</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam risus turpis, aliquet id lobortis a, congue vel nulla. Praesent aliquam dictum enim, vitae bibendum ligula sagittis non. Donec dignissim lobortis lorem vitae aliquam. Proin eget
    turpis dui. Nunc tincidunt neque massa. Pellentesque eu vulputate magna. Duis eros nunc, tempus sit amet tempor eu, cursus ac sem. Fusce et tortor eget lacus facilisis aliquet eu sit amet ligula. Praesent pulvinar imperdiet tincidunt. Nam eros lacus,
    malesuada a dignissim ac, condimentum fringilla nisl. Donec non gravida odio. Morbi et ligula elit. Curabitur elementum facilisis urna et aliquam. Curabitur dignissim scelerisque velit non fermentum.
  </p>
  <p>Nullam dapibus dictum ultrices. In tempus hendrerit arcu eleifend congue. Morbi massa nulla, interdum eu congue id, pretium quis dui. Suspendisse potenti. Etiam nec mattis neque. Proin gravida nulla at tellus ornare vel fringilla purus faucibus.
    Donec vehicula odio ante. Etiam at est nisl, ut elementum justo. Aenean tempor, nibh ut fringilla dignissim, libero eros semper dui, id pretium justo enim at arcu. Morbi lorem mauris, dignissim quis placerat nec, malesuada ut lectus. Nunc auctor
    facilisis nibh non feugiat. Nullam condimentum, libero quis aliquet feugiat, arcu metus accumsan risus, id ornare turpis dui at nisi.
  </p>
  <p>
    Etiam eget magna est. Curabitur iaculis venenatis lectus, vitae imperdiet neque eleifend a. Praesent porttitor placerat condimentum. Morbi tristique dapibus condimentum. Maecenas tellus urna, porta non dignissim eget, ultricies eget massa. Aliquam
    erat volutpat. Nulla facilisi. Fusce pulvinar massa nec nisi fermentum consectetur. Fusce orci est, rhoncus ut rutrum quis, pellentesque eu elit. In dignissim, nibh in elementum commodo, erat elit ultricies odio, nec imperdiet ligula mi vitae felis.
    Aliquam aliquam, orci quis volutpat viverra, mauris sem rhoncus massa, a laoreet metus orci ut odio. Nulla sodales iaculis sapien, quis facilisis nisi accumsan eu. Ut ornare semper commodo. Nam tempus faucibus porttitor. Proin tempus mauris quis dui
    tristique dictum.</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
  <h1>Pages#contact</h1>
  <p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
  <h1>Pages#resources</h1>
  <p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_header.html.erb
<div id="header-wrapper">
  <div id="header">
    <div id="logo">
      <h1>
        <a href="#">My Ruby Blog</a>
      </h1>
    </div>
    <div id="menu">
      <ul class="main-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Resources", resources_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_post_comment.html.erb
<div class="post_comment">
  <i><%=h post_comment.name %> says:</i><br />
  <%= simple_format h(post_comment.body) %>
</div>

app/views/partials/_sidebar.html.erb
<!-- start #sidebar -->
<div id="sidebar">
	<ul>
		<li>
			<div id="search">
				<%= search_form_for @q do |f| %>
					<%= f.search_field :title_or_body_contains %>
					<%= f.submit "Search"%>
				<% end %>
			</div>
			<div style="clear: both;">&nbsp;</div>
		</li>
		<li>
			<h2>Get The Framework</h2>
			<p>You can download Ruby on Rails for free right now
				<br/>
				<a style="color:#D93544;" href="http://rubyonrails.org/download" target="blank">Download</a>
			</p>
		</li>
		<li>
			<h2>Categories</h2>
			<ul>
				<% all_categories.each do |cat| %>
					<li><%= link_to cat.name,category_path(:id => cat.id) %></li>
				<% end %>
			</ul>
		</li>
		<li>
			<h2>Blog Posts</h2>
			<ul>
				<% all_posts.each do |post| %>
					<li><%= link_to post.title,post_path(:id => post.id) %></li>
				<% end %>
			</ul>
		</li>
	</ul>
</div>
<!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <h2 class="title"><%= link_to post.title,post %></h2>
    <div class="entry"><%= post.body %></div>
    <div class="byline">
      <p class="meta">July 09, 2018 Posted by <%= post.admin_user.name%></p>
      <p class="links">
        <%= link_to "Read More",post %>
      </p>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %Y") %></small>
<p>Created by <%= @post.admin_user.name %></p>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name,category_path(:id => @post.category.id) %></p>
<p><%= link_to "Back",posts_path %></p>
<hr/>
<h3>Add A Comment</h3>
<%= form_for @post_comment do|f| %>
  <%= f.hidden_field :post_id %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Post Comment" %>
  </p>
<% end %>
<%= render :partial => 'partials/post_comment', :collection => @post.comments %>